### PR TITLE
update timelock and bug bounty link

### LINKED ISSUE #173: Link to docs for timelock and bug bounty
**Timelock**
https://docs.oeth.com/governance/timelock

**Bug bounty**
https://docs.oeth.com/security-and-risks/bug-bounties

### PR DESCRIPTION
**Pull request by HrikB**
Closes #173

### CODE REVIEW

File: src/homepage/sections/Security.tsx [hunk 1]
```diff
@@ -95,12 +102,19 @@ const Security = ({ audits, sectionOverrideCss }: SecurityProps) => {
...
+              className="mx-auto flex justify-center items-center flex-col"
+              href={"https://docs.oeth.com/security-and-risks/bug-bounties"}
+              target="_blank"
+              rel="noopener noreferrer"
+            >
+              <Image
+                src={assetRootPath("/images/immunefi.svg")}
+                width="180"
+                height="180"
+                alt="lock"
```
Comment (smitch88) [inline src/homepage/sections/Security.tsx:115]: bug? heh

**Review by smitch88 — APPROVED** [review]

File: src/homepage/sections/Security.tsx (hunk 1 above)
Comment (HrikB) [reply src/homepage/sections/Security.tsx:115]: What's wrong?
