### PR TITLE
Staking Apy & other minor changes

### LINKED ISSUE #53: Navigating to Dashboard from Homepage bug
OGV Allocation section is supposed to look like this:
image

But for some reason, when you arrive at the dashboard from the homepage, using the link in the footer, it looks like this:
image

### LINKED ISSUE #54: Wire up staking APY
This is currently hard-coded on the token dashboard and doesn't match the governance dapp.

Screen Shot 2023-01-22 at 8 17 30 PM
Screen Shot 2023-01-22 at 8 17 40 PM
Screen Shot 2023-01-22 at 8 17 50 PM

### LINKED ISSUE #55: Update OGV link in nav
The OGV link in the footer has been updated to point to the new token dashboard, but the one in the nav has not. They should both point to the same place.

### LINKED ISSUE #56: Link excluded wallets to Etherscan
Each of these addresses should link to Etherscan and open in a new tab/window. This is particularly necessary because they are truncated.

Screen Shot 2023-01-22 at 8 24 52 PM

### LINKED ISSUE #57: Scroll to top on route change
When I click the OGV link in the footer, for example, I should not be seeing the footer when the route changes from / to /ogv-dashboard. When navigating forward, I should always start at the top of the document. When navigating backward, I'd be okay with restoring the scroll position to where it was previously, but that's less important.

### LINKED ISSUE #58: Add supply tooltips on mobile
These help icons and associated tooltips are not included on small screens.

Screen Shot 2023-01-23 at 7 59 04 AM

### LINKED ISSUE #59: Broken burn page styling
It looks like some of the OGV dashboard changes cause some side effects for the burn page (primarily line-height).

Screen Shot 2023-01-23 at 12 01 39 PM

### PR DESCRIPTION
**Pull request by HrikB**
Changes included within this PR:
- Routing on header and footer refresh page (on same tab)
- Addresses in circulating supply tooltip link to etherscan
- APY calculation done in `/burn` route has been abstracted for reuse (`useOgv()`). This is then used to wire up the dashboard to the APY
- Tooltip on mobile
- New storybook components update uses tailwind-merge. Fixes burn page and all other pages that were having issues style overrides.

Closes #53 
Closes #54 
Closes #55 
Closes #56 
Closes #57
Closes #58 
Closes #59

### CODE REVIEW

File: src/hooks/useOgv.ts [hunk 1]
```diff
@@ -0,0 +1,65 @@
...
+
+  useEffect(() => {
+    if (!(ogv && veogv)) {
+      return;
+    }
+    const fetchStakedOgv = async () => {
+      const staked = await ogv
+        .balanceOf(addresses.mainnet.veOGV)
+        .then((r) => Number(r) / 10 ** 18);
+      const supply = await ogv.totalSupply().then((r) => Number(r) / 10 ** 18);
```
Comment (shahthepro) [inline src/hooks/useOgv.ts:24]: I guess converting BigNumber to Number and then scaling it to 10^18 decimals is gonna cause rounding and other issues since JS's primitive Number type cannot handle larger numbers.

Would be better and cleaner to do the conversion on BigNumber before casting into Number. Also, could just use `ethers.utils.formatUnits` method

File: src/hooks/useOgv.ts [hunk 2]
```diff
@@ -0,0 +1,65 @@
...
+  const [totalVeSupply, setTotalVeSupply] = useState();
+  const [optionalLockupBalance, setOptionalLockupBalance] = useState();
+  const [mandatoryLockupBalance, setMandatoryLockupBalance] = useState();
+
+  const burnBlock = 15724869;
+
+  useEffect(() => {
+    if (!(ogv && veogv)) {
+      return;
+    }
```
Comment (shahthepro) [inline src/hooks/useOgv.ts:19]: nit: I wonder if we need a `loading` or `error` state as well, so that the UI can handle it properly. Not a blocker or big deal though

**Review by shahthepro — CHANGES_REQUESTED** [review]
A minor concern about numerical operations, otherwise looks good to me

File: src/hooks/useOgv.ts (hunk 1 above)
Comment (HrikB) [reply src/hooks/useOgv.ts]: Done!

**Review by shahthepro — APPROVED** [review]
LGTM, Thanks for addressing the comment
